[package]
name = "first_task"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.cryptography]
path = "/home/mikle/Code/cryptanalysis/cryptography"
